feat: fail pipeline on unknown environment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,6 +31,11 @@ jobs:
 
           echo "env=$ENVIRONMENT" >> $GITHUB_OUTPUT
           echo "tag=$TAG" >> $GITHUB_OUTPUT
+          
+          if [ ! -f "deployment/env/.env.${ENVIRONMENT}" ]; then
+              echo "::error:: File deployment/env/.env.${ENVIRONMENT} does not exist, cannot execute on unknown environment"
+              exit 1
+          fi
 
       - name: Install docker-decompose
         run: npm i -g shawiizz-decomposerize
diff --git a/.gitlab/workflows/deploy.yml b/.gitlab/workflows/deploy.yml
--- a/.gitlab/workflows/deploy.yml
+++ b/.gitlab/workflows/deploy.yml
@@ -1,5 +1,5 @@
 include:
-  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.1/.gitlab/ci-templates/build-steps.yml'
+  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.2/.gitlab/ci-templates/build-steps.yml'
 
 stages:
   - deploy
@@ -28,6 +28,11 @@ stages:
   
       export ENV=$ENVIRONMENT
       export VERSION=$TAG
+      
+      if [ ! -f "deployment/env/.env.${ENVIRONMENT}" ]; then
+          echo "File deployment/env/.env.${ENVIRONMENT} does not exist, cannot execute on unknown environment"
+          exit 1
+      fi
 
 deploy:build:
   stage: deploy-build
